blank_issues_enabled: false
contact_links:
  - name: famhawiteinfosys Projects Community
    url: https://t.me/famhawiteinfosysSupport
    about: Join our community chat to get your questions answered easily!
